### PR TITLE
Added tests for question stats, answer stats and try_cast_int

### PR DESCRIPTION
**Pull request by rohithpr**
Take a look at this. I'll add more if this is fine.

### CODE REVIEW

**Comment by rohithpr** [comment]
:/ There are too many errors caused by non-ascii characters. We have to move to Py3...

**Comment by csu** [comment]
Yeah, we need to prioritize #24.

**Comment by rohithpr** [comment]
@csu take a look at [this](https://travis-ci.org/csu/pyquora/jobs/47680398). I'm unable to figure it out. PS: This is a test that was there before, I haven't changed that file.

**Comment by rohithpr** [comment]
@csu I guess I'm done writing tests for now. :sweat_smile:

Merge it maybe? :p

**Comment by csu** [comment]
Looks good. Thanks! I'll refactor it a bit after merging, but good work!

**Pull request merged**
