### PR TITLE
Avoid construction of dictionary to check whether an answer was found

### PR DESCRIPTION
**Pull request by svisser**
Minor simplification to the code by not constructing an unnecessary dictionary.

### CODE REVIEW

**Comment by rohithpr** [comment]
That is from back when get_one_answer() would return an empty dictionary if any error had occurred. :D Checking is pointless now.
I think its best to put the function call within a try block and ignoring any errors. Since we are generating random strings and making the function call, there will be errors every now and then.

**Comment by svisser** [comment]
But get_one_answer still returns an empty dictionary in case of an error, right? It's possible to remove the try/except in get_one_answer but then the API changes: it means every user of get_one_answer needs (or is recommended) to wrap with try/except.

If anything, I'd keep thing as they are now but let get_one_answer return a valid dictionary in case of an answer or `None` in case the answer could not be obtained.

**Comment by rohithpr** [comment]
Oops. I thought it didn't return an empty dict in case of an error. The change was made to another function [#43](https://github.com/csu/pyquora/pull/43/).

**Comment by csu** [comment]
Looks good. If we ever change the API for `get_one_answer`, we'll want to come back and look at this, but for now, it's fine.

**Pull request merged**
