### PR TITLE
Separated `Quora` to `User` and `Quora`!  #41

### PR DESCRIPTION
**Pull request by rohithpr**
I've done some basic testing.
One of you will have to work on "User". I'm not very comfortable with that and I'm afraid of breaking things! :p

### CODE REVIEW

**Comment by csu** [comment]
Any updates here?

**Comment by rohithpr** [comment]
I wasn't sure what was to be done! :tongue:

**Comment by rohithpr** [comment]
That's it right? Is there anything else that can be converted into a property?

**Comment by csu** [comment]
Yeah, I think it's just stats and activity for now. Looks good. We might want to reconsider the file names and organization later, but I think this can be merged now. Can you resolve the merge conflicts (just pull master into your pull request branch) so the PR can be automatically merged?

**Comment by rohithpr** [comment]
Its done.

**Comment by csu** [comment]
Merging now. Hopefully this doesn't break everything :stuck_out_tongue:

**Pull request merged**
